# Generated by Django 3.2.8 on 2021-10-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20211026_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='album_artist',
            new_name='artist',
        ),
    ]
