# Generated by Django 3.2.8 on 2021-10-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_members'),
        ('albums', '0003_rename_album_artist_albums_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist'),
        ),
    ]
